server:
  port: 50051
  timeout: 30s

database:
  host: "auth_db"
  port: 5432
  name: "auth_db"
  user: "auth_user"
  password: "password"
  ssl_mode: "disable"

jwt:
  secret: "secret-key"
  access_ttl: "15m" 
  refresh_ttl: "168h"

logging:
  level: "info"