server:
  port: 8080
  timeout: 30s

services:
  auth:
    address: "dns:///auth-service:50051"
    timeout: 5s
  event:
    address: "dns:///event-service:50052" 
    timeout: 5s


logging:
  level: "info"